{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "database-secrets",
    "namespace": "plant-tracker"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "database-secrets",
        "namespace": "plant-tracker"
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "password": "AgCthYzqQU0DG1ewRyAvAiqaYcytFK8laMEpIZ63AYGV2eNf7YuCBMsr50FMjlKdYL3Pv7b6bgv1lhpa8J3PD5FA4AePDFYpwy3Y55yiSJ/14PjVVu3EVNdQzz5xq95DW0LtQsy8HhCfIuMqvsAv2xYCYFFKaDjXB6p9kXpQBJ4Cz6dvUwWi9xDRsHIu6eNU4RSk4DyX+6qyF3FSxTiximdS+Xb0uRo4N9MQ2ADtgHRef+rAfAVS003gQgN2lXqqQohS9JJYm0Vqk7AW4EuHFwjp8DVe91iJ/6MAjWZv6fkN3n4st+IW69ZeJwrBk0qLs6B4LjOXcbvlW7+yGZybYZvm6Yc3XpzvO5Ff+tX+FR3oBaBjS+82/XfzZGnCKLufCuB/x1b04Rf2hOP8eqScrb7cqBaxXSxT3HxAMXrjjd082W597++m3XHtu+hhYQZkERrBZTpEZ+3Z1agLFIlJmqoNc5DOUPZWT97QVXOAn0/OjhoU3CDOt6z8aHgItBJVovpQEqfXWQL5cmWooVFZd2j2Wes2TtWYg0MktUR4KUSFta4d+Fi+gil5l/SWiyftVzbYHrHk5Z3SPKbJ7b+5xv91V5kaugEl39ycIfSnrlyjY9ZTppf1TScGgLX/vMpV3zc/mQ0LSiwFtv7rtcLgvGjiJ9f2vF7yOMaAyDpVhXr9VE4bW5GdJvPBQE8bATJkYyDii3lstOOJyByQHwRR6a8D/o2J",
      "url": "AgA9Lx1icS6j4hjWE/YVyybdf7/ug1VzNOQFsgiD+E4M0CzXaq/Z4K3SnMVbEMKF5jZ3jEnCuTnEOEQvHIpHZ1TbSmGtin+vWeYZI151Ar4riBbk225qtAaxC87N4WmWMHCjsdwvfMPOUm8q2cyrmfUbfn0sGFkq6BxmX6+auRX/o9k8sL3sQrCbUe8zt46hFCVGJ9a3PDEUTVuDQNecyjl6B6JWsis2SWSEjGAY81Ed0SuGvtd0FVI3BFhJLJyrWDvYSq5OV+yVFA004r1xfeE/XvktU3tS/L7yjaA63PSFBF/ha0tVxKRgvni6DQ4rqH72m+kQEBUPRt7wlX82ao3vmuOrQ+JPd3sfHCco7y7khNrlVIrHey0pnY+ryGV3Pa++Xyb25m2t/a1M9ne+snsOSbplg3F4zN1N6zzuhtO++7G/aJo3HOxESYLyAwKPnObytDAxrc0dwohA3yoEaCYa6WO+V+Q7ppVOIw5f52ppeJ2ql4Cz/KZV8AKbb/uHYcCg/vSP0eiM5Z24+tHPnX7E1tMXakauUTcCCsek7fxdnirGm9/AEKsJLMFErQ6eXVixUnniVdKcg1IoKZF19rm/YdtkSiSbdQkVAlh62B2gNOZBgtDCrWXhke+ML1I+Q+y6wrtZyaepczmvT2APdawkVz2235Bvj1gHdmlPUoPiZy/CrLqhI0Y8af/NhPtt9zqJU4frVlDc64RquA4t7ZFEwezau5SiCy3aNEaiP/vAB2rKY+IawL4QahfIIhex26YNobLYMErx1as+pihQTbQeoFhIcr26sNlcaB3t3Q=="
    }
  }
}
